name: links

on: 
  push:
    branches:
    - main
  pull_request:
  schedule:
  - cron: '0 14 * * 1-5'

jobs:
  check_links:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout source code
      uses: actions/checkout@master

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn add markdown-link-extractor@4.0.1 axios@1.2.0

    - name: Check links
      run: |
          JS_FILE=${{ secrets.JS_FILE }}
          JS_FILE=${JS_FILE:-"https://gist.githubusercontent.com/hibuz/831124fa3baf6eb173e99611c03ed6ed/raw/476d7e1f65e19f35f318a536420568c05a400e66/links.mjs"}
          curl --silent --output index.mjs ${JS_FILE}
          node index.mjs
